[build]
dockerfilePath = "Dockerfile"
dockerBuildArgs = ["DATA_ENCRYPTION_KEY"]

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
